# Generated by Django 3.1.1 on 2024-04-13 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_fuelprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelprice',
            old_name='diesel',
            new_name='Diesel',
        ),
        migrations.RenameField(
            model_name='fuelprice',
            old_name='lpg',
            new_name='LPG',
        ),
        migrations.RenameField(
            model_name='fuelprice',
            old_name='petrol',
            new_name='Petrol',
        ),
    ]
